package com.example.quanta.navigation

const val ROUT_HOME="home"
const val ROUT_MENU="menu"
const val ROUT_SPLASH="splash"
const val ROUT_SIGNUP="signup"
const val ROUT_LOGIN="login"
const val ROUT_CONTACT="contact"
const val ROUT_NOTIFICATION="notification"
const val ROUT_CRUISER="cruiser"
const val ROUT_ROVER="rover"
const val ROUT_PORSCHE="porsche"
const val ROUT_TESLA="tesla"
const val ROUT_BMW="bmw"
const val ROUT_DEFENDER="defender"
const val ADD_PRODUCTS_URL = "add_products"
const val VIEW_PRODUCTS_URL = "view_products"
